<?php

use Illuminate\Database\Seeder;

class KabupatenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =
        [
            ['id'=>   1   , 'nama_kabupaten' => 'Aceh Selatan', 'provinsi_id'    =>  11],
            ['id'=>   2   , 'nama_kabupaten' => 'Simeulue    ', 'provinsi_id'    =>  11],
            ['id'=>   3   , 'nama_kabupaten' => 'Aceh Tenggara', 'provinsi_id'   =>  11],
            ['id'=>   4   , 'nama_kabupaten' => 'Aceh Timur', 'provinsi_id'      =>  11],
            ['id'=>   5   , 'nama_kabupaten' => 'Aceh Tengah', 'provinsi_id'     =>  11],
            ['id'=>   6   , 'nama_kabupaten' => 'Aceh Barat', 'provinsi_id'      =>  11],
            ['id'=>   7   , 'nama_kabupaten' => 'Aceh Besar', 'provinsi_id'      =>  11],
            ['id'=>   8   , 'nama_kabupaten' => 'Pidie   ', 'provinsi_id'        =>  11],
            ['id'=>   9   , 'nama_kabupaten' => 'Aceh Utara', 'provinsi_id'      =>  11],
            ['id'=>   10  , 'nama_kabupaten' => 'Simeulue      ', 'provinsi_id'  =>  11],
            ['id'=>   11  , 'nama_kabupaten' => 'Aceh Singkil', 'provinsi_id'    =>  11],
            ['id'=>   12  , 'nama_kabupaten' => 'Bireuen ', 'provinsi_id'        =>  11],
            ['id'=>   13  , 'nama_kabupaten' => 'Aceh BaratDaya', 'provinsi_id'  =>  11],
            ['id'=>   14  , 'nama_kabupaten' => 'Gayo Lues', 'provinsi_id'       =>  11],
            ['id'=>   15  , 'nama_kabupaten' => 'Aceh Jaya', 'provinsi_id'       =>  11],
            ['id'=>   16  , 'nama_kabupaten' => 'Nagan Raya', 'provinsi_id'      =>  11],
            ['id'=>   17  , 'nama_kabupaten' => 'Aceh Tamiang', 'provinsi_id'    =>  11],
            ['id'=>   18  , 'nama_kabupaten' => 'Aceh Jaya', 'provinsi_id'       =>  11],
            ['id'=>   19  , 'nama_kabupaten' => 'Bener Meriah', 'provinsi_id'    =>  11],
            ['id'=>   20  , 'nama_kabupaten' => 'Pidie Jaya', 'provinsi_id'      =>  11],
            ['id'=>   21  , 'nama_kabupaten' => 'Kota Banda Aceh ', 'provinsi_id'=>  11],
            ['id'=>   22  , 'nama_kabupaten' => 'Kota Sabang', 'provinsi_id'     =>  11],
            ['id'=>   23  , 'nama_kabupaten' => 'Kota Lhokseumawe', 'provinsi_id'=>  11],
            ['id'=>   24  , 'nama_kabupaten' => 'Kota Langsa', 'provinsi_id'     =>  11],
            ['id'=>   25  , 'nama_kabupaten' => 'Kota Subulussalam', 'provinsi_id'=> 11],
            ['id'=>   26  , 'nama_kabupaten' => 'Tapanuli Tengah', 'provinsi_id' =>  12],
            ['id'=>   27  , 'nama_kabupaten' => 'Tapanuli Utara', 'provinsi_id'  =>  12],
            ['id'=>   28  , 'nama_kabupaten' => 'Tapanuli Selatan', 'provinsi_id'=>  12],
            ['id'=>   29  , 'nama_kabupaten' => 'Nias    ', 'provinsi_id'        =>  12],
            ['id'=>   30  , 'nama_kabupaten' => 'Langkat ', 'provinsi_id'        =>  12],
            ['id'=>   31  , 'nama_kabupaten' => 'Karo    ', 'provinsi_id'        =>  12],
            ['id'=>   32  , 'nama_kabupaten' => 'Deli Serdang', 'provinsi_id'    =>  12],
            ['id'=>   33  , 'nama_kabupaten' => 'Simalungun  ', 'provinsi_id'    =>  12],
            ['id'=>   34  , 'nama_kabupaten' => 'Asahan  ', 'provinsi_id'        =>  12],
            ['id'=>   35  , 'nama_kabupaten' => 'Labuhan Batu', 'provinsi_id'    =>  12],
            ['id'=>   36  , 'nama_kabupaten' => 'Dairi   ', 'provinsi_id'        =>  12],
            ['id'=>   37  , 'nama_kabupaten' => 'Toba Samosir', 'provinsi_id' =>     12],
            ['id'=>   38  , 'nama_kabupaten' => 'Mandailing Natal', 'provinsi_id' => 12],
            ['id'=>   39  , 'nama_kabupaten' => 'Nias Selatan', 'provinsi_id' =>     12],
            ['id'=>   40  , 'nama_kabupaten' => 'Pakpak Bharat', 'provinsi_id' =>    12],
            ['id'=>   41  , 'nama_kabupaten' => 'Humbang Hasundutan', 'provinsi_id'=>12],
            ['id'=>   42  , 'nama_kabupaten' => 'Samosir ', 'provinsi_id'          =>12],
            ['id'=>   43  , 'nama_kabupaten' => 'Serdang Bedagai', 'provinsi_id' =>  12],
            ['id'=>   44  , 'nama_kabupaten' => 'Padang Lawas', 'provinsi_id' =>     12],
            ['id'=>   45  , 'nama_kabupaten' => 'Padang Lawas Utara', 'provinsi_id'=>12],
            ['id'=>   46  , 'nama_kabupaten' => 'Batu Bara', 'provinsi_id'       =>  12],
            ['id'=>   47  , 'nama_kabupaten' => 'Labuhan Batu Selatan', 'provinsi_id'=>12],
            ['id'=>   48  , 'nama_kabupaten' => 'Labuhan Batu Utara', 'provinsi_id' =>12],
            ['id'=>   49  , 'nama_kabupaten' => 'Nias Barat', 'provinsi_id'      =>  12],
            ['id'=>   50  , 'nama_kabupaten' => 'Nias Utara', 'provinsi_id'      =>  12],
            ['id'=>   51  , 'nama_kabupaten' => 'Kota Medan', 'provinsi_id'      =>  12],
            ['id'=>   52  , 'nama_kabupaten' => 'Kota Pematang Siantar', 'provinsi_id'=>12],
            ['id'=>   53  , 'nama_kabupaten' => 'Kota Sibolga', 'provinsi_id' =>    12],
            ['id'=>   54  , 'nama_kabupaten' => 'Kota Tanjung Balai', 'provinsi_id'=> 12],
            ['id'=>   55  , 'nama_kabupaten' => 'Kota Binjai', 'provinsi_id' => 12],
            ['id'=>   56  , 'nama_kabupaten' => 'Kota Tebing Tinggi', 'provinsi_id' => 12],
            ['id'=>   57  , 'nama_kabupaten' => 'Kota Padangsidimpuan', 'provinsi_id' =>12],
            ['id'=>   58  , 'nama_kabupaten' => 'Kota Gunungsitoli', 'provinsi_id' => 12],
            ['id'=>   59  , 'nama_kabupaten' => 'Pesisir Selatan', 'provinsi_id' => 13],
            ['id'=>   60  , 'nama_kabupaten' => 'Solok ', 'provinsi_id'          =>13],
            ['id'=>   61  , 'nama_kabupaten' => 'Sijunjung ', 'provinsi_id'      =>13],
            ['id'=>   62  , 'nama_kabupaten' => 'Tanah Datar', 'provinsi_id'     => 13],
            ['id'=>   63  , 'nama_kabupaten' => 'Padang Pariaman', 'provinsi_id' => 13],
            ['id'=>   64  , 'nama_kabupaten' => 'Agam', 'provinsi_id'        =>13],
            ['id'=>   65  , 'nama_kabupaten' => 'Lima Puluh Kota', 'provinsi_id' => 13],
            ['id'=>   66  , 'nama_kabupaten' => 'Pasaman ', 'provinsi_id'        =>13],
            ['id'=>   67  , 'nama_kabupaten' => 'Kepulauan Mentawai', 'provinsi_id'=>  13],
            ['id'=>   68  , 'nama_kabupaten' => 'Dharmasraya ', 'provinsi_id' => 13],
            ['id'=>   69  , 'nama_kabupaten' => 'Solok Selatan', 'provinsi_id' =>   13],
            ['id'=>   70  , 'nama_kabupaten' => 'Pasaman Barat', 'provinsi_id' =>   13],
            ['id'=>   71  , 'nama_kabupaten' => 'Kota Padang', 'provinsi_id' => 13],
            ['id'=>   72  , 'nama_kabupaten' => 'Kota Solok', 'provinsi_id' =>  13],
            ['id'=>   73  , 'nama_kabupaten' => 'Kota Sawah Lunto', 'provinsi_id' => 13],
            ['id'=>   74  , 'nama_kabupaten' => 'Kota Padang Panjang', 'provinsi_id' => 13],
            ['id'=>   75  , 'nama_kabupaten' => 'Kota Bukittinggi', 'provinsi_id' =>    13],
            ['id'=>   76  , 'nama_kabupaten' => 'Kota Payakumbuh', 'provinsi_id' => 13],
            ['id'=>   77  , 'nama_kabupaten' => 'Kota Pariaman', 'provinsi_id' =>   13],
            ['id'=>   78  , 'nama_kabupaten' => 'Kampar  ', 'provinsi_id'        =>14],
            ['id'=>   79  , 'nama_kabupaten' => 'Indragiri Hulu', 'provinsi_id' =>  14],
            ['id'=>   80  , 'nama_kabupaten' => 'Bengkalis   ', 'provinsi_id' =>   14],
            ['id'=>   81  , 'nama_kabupaten' => 'Indragiri Hilir', 'provinsi_id' => 14],
            ['id'=>   82  , 'nama_kabupaten' => 'Pelalawan   ', 'provinsi_id' =>14],
            ['id'=>   83  , 'nama_kabupaten' => 'Rokan Hulu', 'provinsi_id' =>  14],
            ['id'=>   84  , 'nama_kabupaten' => 'Rokan Hilir', 'provinsi_id' => 14],
            ['id'=>   85  , 'nama_kabupaten' => 'Siak    ', 'provinsi_id' =>14],
            ['id'=>   86  , 'nama_kabupaten' => 'Kuantan Singingi', 'provinsi_id' =>    14],
            ['id'=>   87  , 'nama_kabupaten' => 'Kepulauan Meranti', 'provinsi_id' =>   14],
            ['id'=>   88  , 'nama_kabupaten' => 'Kota Pekanbaru', 'provinsi_id' =>  14],
            ['id'=>   89  , 'nama_kabupaten' => 'Kota Dumai', 'provinsi_id' =>  14],
            ['id'=>   90  , 'nama_kabupaten' => 'Kerinci', 'provinsi_id' =>15],
            ['id'=>   91  , 'nama_kabupaten' => 'Merangin ', 'provinsi_id' =>15],
            ['id'=>   92  , 'nama_kabupaten' => 'Sarolangun ', 'provinsi_id' =>15],
            ['id'=>   93  , 'nama_kabupaten' => 'Batang Hari', 'provinsi_id' => 15],
            ['id'=>   94  , 'nama_kabupaten' => 'Muaro Jambi', 'provinsi_id' => 15],
            ['id'=>   95  , 'nama_kabupaten' => 'Tanjung Jabung Barat', 'provinsi_id' => 15],
            ['id'=>   96  , 'nama_kabupaten' => 'Tanjung Jabung Timur', 'provinsi_id' => 15],
            ['id'=>   97  , 'nama_kabupaten' => 'Bungo', 'provinsi_id'                => 15],
            ['id'=>   98  , 'nama_kabupaten' => 'Tebo    ', 'provinsi_id'              =>15],
            ['id'=>   99  , 'nama_kabupaten' => 'Kota Jambi', 'provinsi_id'          =>  15],
            ['id'=>   100, 'nama_kabupaten' => 'Kota Sungai Penuh', 'provinsi_id'    => 15],
            ['id'=>   101, 'nama_kabupaten' => 'Ogan Komering Ulu', 'provinsi_id'    => 16],
            ['id'=>   102, 'nama_kabupaten' => 'Ogan Komering Ilir', 'provinsi_id'   => 16],
            ['id'=>   103, 'nama_kabupaten' => 'Muara Enim', 'provinsi_id'           => 16],
            ['id'=>   104, 'nama_kabupaten' => 'Lahat   ', 'provinsi_id'             => 16],
            ['id'=>   105, 'nama_kabupaten' => 'Musi Rawas', 'provinsi_id'           => 16],
            ['id'=>   106, 'nama_kabupaten' => 'Musi Banyuasin', 'provinsi_id'       => 16],
            ['id'=>   107, 'nama_kabupaten' => 'Banyuasin', 'provinsi_id'            => 16],
            ['id'=>   108, 'nama_kabupaten' => 'Ogan Komering Ulu Timur', 'provinsi_id' => 16],
            ['id'=>   109, 'nama_kabupaten' => 'Ogan Komering Ulu Selatan', 'provinsi_id' => 16],
            ['id'=>   110, 'nama_kabupaten' => 'Ogan Ilir', 'provinsi_id'            => 16],
            ['id'=>   111, 'nama_kabupaten' => 'Empat Lawang', 'provinsi_id'         => 16],
            ['id'=>   112, 'nama_kabupaten' => 'Penukal Abab Lematang Ilir', 'provinsi_id' => 16],
            ['id'=>   113, 'nama_kabupaten' => 'Musi Rawas Utara', 'provinsi_id'         => 16],
            ['id'=>   114, 'nama_kabupaten' => 'Kota Palembang', 'provinsi_id'           => 16],
            ['id'=>   115, 'nama_kabupaten' => 'Kota Pagar Alam', 'provinsi_id' => 16],
            ['id'=>   116, 'nama_kabupaten' => 'Kota Lubuklinggau', 'provinsi_id' =>   16],
            ['id'=>   117, 'nama_kabupaten' => 'Kota Prabumulih', 'provinsi_id' => 16],
            ['id'=>   118, 'nama_kabupaten' => 'Bengkulu Selatan', 'provinsi_id' =>    17],
            ['id'=>   119, 'nama_kabupaten' => 'Rejang Lebong', 'provinsi_id' =>   17],
            ['id'=>   120, 'nama_kabupaten' => 'Bengkulu Utara', 'provinsi_id' =>  17],
            ['id'=>   121, 'nama_kabupaten' => 'Kaur', 'provinsi_id'            =>17],
            ['id'=>   122, 'nama_kabupaten' => 'Seluma  ', 'provinsi_id'        => 17],
            ['id'=>   123, 'nama_kabupaten' => 'Mukomuko   ', 'provinsi_id'      =>17],
            ['id'=>   124, 'nama_kabupaten' => 'Lebong  ', 'provinsi_id'         =>17],
            ['id'=>   125, 'nama_kabupaten' => 'Kepahiang   ', 'provinsi_id' => 17],
            ['id'=>   126, 'nama_kabupaten' => 'Bengkulu Tengah', 'provinsi_id' => 17],
            ['id'=>   127, 'nama_kabupaten' => 'Kota Bengkulu', 'provinsi_id' =>   17],
            ['id'=>   128, 'nama_kabupaten' => 'Lampung Selatan', 'provinsi_id' => 18],
            ['id'=>   129, 'nama_kabupaten' => 'Lampung Tengah', 'provinsi_id' =>  18],
            ['id'=>   130, 'nama_kabupaten' => 'Lampung Utara', 'provinsi_id' =>   18],
            ['id'=>   131, 'nama_kabupaten' => 'Lampung Barat', 'provinsi_id' =>   18],
            ['id'=>   132, 'nama_kabupaten' => 'Tulangbawang ', 'provinsi_id'   => 18],
            ['id'=>   133, 'nama_kabupaten' => 'Tanggamus  ', 'provinsi_id'   => 18],
            ['id'=>   134, 'nama_kabupaten' => 'Lampung Timur', 'provinsi_id' =>  18],
            ['id'=>   135, 'nama_kabupaten' => 'Way Kanan', 'provinsi_id' =>   18],
            ['id'=>   136, 'nama_kabupaten' => 'Pesawaran  ', 'provinsi_id' => 18],
            ['id'=>   137, 'nama_kabupaten' => 'Pringsewu  ', 'provinsi_id' => 18],
            ['id'=>   138, 'nama_kabupaten' => 'Tulang Bawang Barat', 'provinsi_id' => 18],
            ['id'=>   139, 'nama_kabupaten' => 'Mesuji', 'provinsi_id'               =>18],
            ['id'=>   140, 'nama_kabupaten' => 'Pesisir Barat', 'provinsi_id'        =>18],
            ['id'=>   141, 'nama_kabupaten' => 'Kota Bandar Lampung', 'provinsi_id'=> 18],
            ['id'=>   142, 'nama_kabupaten' => 'Kota Metro', 'provinsi_id'        =>  18],
            ['id'=>   143, 'nama_kabupaten' => 'Bangka  ', 'provinsi_id'       =>   19],
            ['id'=>   144, 'nama_kabupaten' => 'Belitung    ', 'provinsi_id'      =>19],
            ['id'=>   145, 'nama_kabupaten' => 'Bangka Selatan', 'provinsi_id' =>  19],
            ['id'=>   146, 'nama_kabupaten' => 'Bangka Tengah', 'provinsi_id' =>   19],
            ['id'=>   147, 'nama_kabupaten' => 'Bangka Barat', 'provinsi_id' =>    19],
            ['id'=>   148, 'nama_kabupaten' => 'Belitung Timur', 'provinsi_id' =>  19],
            ['id'=>   149, 'nama_kabupaten' => 'Kota Pangkal Pinang', 'provinsi_id' => 19],
            ['id'=>   150, 'nama_kabupaten' => 'Bintan  ', 'provinsi_id'             =>21],
            ['id'=>   151, 'nama_kabupaten' => 'Karimun ', 'provinsi_id'           =>21],
            ['id'=>   152, 'nama_kabupaten' => 'Natuna  ', 'provinsi_id'           =>21],
            ['id'=>   153, 'nama_kabupaten' => 'Lingga  ', 'provinsi_id'         =>21],
            ['id'=>   154, 'nama_kabupaten' => 'Kepulauan Anambas', 'provinsi_id' => 21],
            ['id'=>   155, 'nama_kabupaten' => 'Kota Batam', 'provinsi_id' =>  21],
            ['id'=>   156, 'nama_kabupaten' => 'Kota Tanjung Pinang', 'provinsi_id' => 21],
            ['id'=>   157, 'nama_kabupaten' => 'Kepulauan Seribu', 'provinsi_id' =>    31],
            ['id'=>   158, 'nama_kabupaten' => 'Kota Jakarta Pusat', 'provinsi_id' => 31],
            ['id'=>   159, 'nama_kabupaten' => 'Kota Jakarta Utara', 'provinsi_id' => 31],
            ['id'=>   160, 'nama_kabupaten' => 'Kota Jakarta Barat', 'provinsi_id' => 31],
            ['id'=>   161, 'nama_kabupaten' => 'Kota Jakarta Selatan', 'provinsi_id' =>31],
            ['id'=>   162, 'nama_kabupaten' => 'Kota Jakarta Timur', 'provinsi_id' => 31],
            ['id'=>   163, 'nama_kabupaten' => 'Bogor', 'provinsi_id'                =>32],
            ['id'=>   164, 'nama_kabupaten' => 'Sukabumi    ', 'provinsi_id'       =>32],
            ['id'=>   165, 'nama_kabupaten' => 'Cianjur ', 'provinsi_id'           =>32],
            ['id'=>   166, 'nama_kabupaten' => 'Bandung ', 'provinsi_id'           =>32],
            ['id'=>   167, 'nama_kabupaten' => 'Garut   ', 'provinsi_id'           =>32],
            ['id'=>   168, 'nama_kabupaten' => 'Tasikmalaya ', 'provinsi_id'       =>32],
            ['id'=>   169, 'nama_kabupaten' => 'Ciamis  ', 'provinsi_id'           =>32],
            ['id'=>   170, 'nama_kabupaten' => 'Kuningan    ', 'provinsi_id'       =>32],
            ['id'=>   171, 'nama_kabupaten' => 'Cirebon ', 'provinsi_id'          =>32],
            ['id'=>   172, 'nama_kabupaten' => 'Majalengka', 'provinsi_id'   =>32],
            ['id'=>   173, 'nama_kabupaten' => 'Sumedang  ', 'provinsi_id'   =>32],
            ['id'=>   174, 'nama_kabupaten' => 'Indramayu ', 'provinsi_id'   =>32],
            ['id'=>   175, 'nama_kabupaten' => 'Subang  ', 'provinsi_id'       =>32],
            ['id'=>   176, 'nama_kabupaten' => 'Purwakarta', 'provinsi_id' =>32],
            ['id'=>   177, 'nama_kabupaten' => 'Karawang ', 'provinsi_id' =>32],
            ['id'=>   178, 'nama_kabupaten' => 'Bekasi  ', 'provinsi_id' =>32],
            ['id'=>   179, 'nama_kabupaten' => 'Bandung Barat', 'provinsi_id' =>   32],
            ['id'=>   180, 'nama_kabupaten' => 'Pangandaran', 'provinsi_id' => 32],
            ['id'=>   181, 'nama_kabupaten' => 'Kota Bogor', 'provinsi_id' =>  32],
            ['id'=>   182, 'nama_kabupaten' => 'Kota Sukabumi', 'provinsi_id' =>32],
            ['id'=>   183, 'nama_kabupaten' => 'Kota Bandung', 'provinsi_id' => 32],
            ['id'=>   184, 'nama_kabupaten' => 'Kota Cirebon', 'provinsi_id' => 32],
            ['id'=>   185, 'nama_kabupaten' => 'Kota Bekasi', 'provinsi_id' => 32],
            ['id'=>   186, 'nama_kabupaten' => 'Kota Depok', 'provinsi_id' =>  32],
            ['id'=>   187, 'nama_kabupaten' => 'Kota Cimahi', 'provinsi_id' => 32],
            ['id'=>   188, 'nama_kabupaten' => 'Kota Tasikmalaya', 'provinsi_id' =>32],
            ['id'=>   189, 'nama_kabupaten' => 'Kota Banjar', 'provinsi_id' => 32],
            ['id'=>   190, 'nama_kabupaten' => 'Cilacap', 'provinsi_id' =>33],
            ['id'=>   191, 'nama_kabupaten' => 'Banyumas', 'provinsi_id' =>33],
            ['id'=>   192, 'nama_kabupaten' => 'Purbalingga', 'provinsi_id' =>33],
            ['id'=>   193, 'nama_kabupaten' => 'Banjarnegara', 'provinsi_id' =>33],
            ['id'=>   194, 'nama_kabupaten' => 'Kebumen', 'provinsi_id' =>33],
            ['id'=>   195, 'nama_kabupaten' => 'Purworejo', 'provinsi_id' =>33],
            ['id'=>   196, 'nama_kabupaten' => 'Wonosobo', 'provinsi_id' =>33],
            ['id'=>   197, 'nama_kabupaten' => 'Magelang', 'provinsi_id' =>33],
            ['id'=>   198, 'nama_kabupaten' => 'Boyolali', 'provinsi_id' =>33],
            ['id'=>   199, 'nama_kabupaten' => 'Klaten ', 'provinsi_id' =>33],
            ['id'=>   200, 'nama_kabupaten' => 'Sukoharjo ', 'provinsi_id' =>33],
            ['id'=>   201, 'nama_kabupaten' => 'Wonogiri  ', 'provinsi_id' =>33],
            ['id'=>   202, 'nama_kabupaten' => 'Karanganyar', 'provinsi_id' =>33],
            ['id'=>   203, 'nama_kabupaten' => 'Sragen', 'provinsi_id' =>33],
            ['id'=>   204, 'nama_kabupaten' => 'Grobogan', 'provinsi_id' =>33],
            ['id'=>   205, 'nama_kabupaten' => 'Blora   ', 'provinsi_id' =>33],
            ['id'=>   206, 'nama_kabupaten' => 'Rembang ', 'provinsi_id' =>33],
            ['id'=>   207, 'nama_kabupaten' => 'Pati    ', 'provinsi_id' =>33],
            ['id'=>   208, 'nama_kabupaten' => 'Kudus   ', 'provinsi_id' =>33],
            ['id'=>   209, 'nama_kabupaten' => 'Jepara  ', 'provinsi_id' =>33],
            ['id'=>   210, 'nama_kabupaten' => 'Demak   ', 'provinsi_id' =>33],
            ['id'=>   211, 'nama_kabupaten' => 'Semarang  ', 'provinsi_id' =>33],
            ['id'=>   212, 'nama_kabupaten' => 'Temanggung', 'provinsi_id' =>33],
            ['id'=>   213, 'nama_kabupaten' => 'Kendal  ', 'provinsi_id' =>33],
            ['id'=>   214, 'nama_kabupaten' => 'Batang  ', 'provinsi_id' =>33],
            ['id'=>   215, 'nama_kabupaten' => 'Pekalongan ', 'provinsi_id' =>33],
            ['id'=>   216, 'nama_kabupaten' => 'Pemalang', 'provinsi_id' =>33],
            ['id'=>   217, 'nama_kabupaten' => 'Tegal   ', 'provinsi_id' =>33],
            ['id'=>   218, 'nama_kabupaten' => 'Brebes  ', 'provinsi_id' =>33],
            ['id'=>   219, 'nama_kabupaten' => 'Kota Magelang', 'provinsi_id' =>   33],
            ['id'=>   220, 'nama_kabupaten' => 'Kota Surakarta', 'provinsi_id' =>  33],
            ['id'=>   221, 'nama_kabupaten' => 'Kota Salatiga', 'provinsi_id' =>   33],
            ['id'=>   222, 'nama_kabupaten' => 'Kota Semarang', 'provinsi_id' =>   33],
            ['id'=>   223, 'nama_kabupaten' => 'Kota Pekalongan', 'provinsi_id' => 33],
            ['id'=>   224, 'nama_kabupaten' => 'Kota Tegal', 'provinsi_id' =>  33],
            ['id'=>   225, 'nama_kabupaten' => 'Kulon Progo', 'provinsi_id' => 34],
            ['id'=>   226, 'nama_kabupaten' => 'Bantul  ', 'provinsi_id'   =>34],
            ['id'=>   227, 'nama_kabupaten' => 'Gunung Kidul', 'provinsi_id' =>  34],
            ['id'=>   228, 'nama_kabupaten' => 'Sleman  ', 'provinsi_id' =>34],
            ['id'=>   229, 'nama_kabupaten' => 'Kota Yogyakarta', 'provinsi_id' => 34],
            ['id'=>   230, 'nama_kabupaten' => 'Pacitan', 'provinsi_id' =>35],
            ['id'=>   231, 'nama_kabupaten' => 'Ponorogo', 'provinsi_id' =>35],
            ['id'=>   232, 'nama_kabupaten' => 'Trenggalek', 'provinsi_id' =>35],
            ['id'=>   233, 'nama_kabupaten' => 'Tulungagung', 'provinsi_id' =>35],
            ['id'=>   234, 'nama_kabupaten' => 'Blitar', 'provinsi_id' =>35],
            ['id'=>   235, 'nama_kabupaten' => 'Kediri', 'provinsi_id' =>35],
            ['id'=>   236, 'nama_kabupaten' => 'Malang', 'provinsi_id' =>35],
            ['id'=>   237, 'nama_kabupaten' => 'Lumajang', 'provinsi_id' =>35],
            ['id'=>   238, 'nama_kabupaten' => 'Jember', 'provinsi_id' =>35],
            ['id'=>   239, 'nama_kabupaten' => 'Banyuwangi', 'provinsi_id' =>35],
            ['id'=>   240, 'nama_kabupaten' => 'Bondowoso', 'provinsi_id' =>35],
            ['id'=>   241, 'nama_kabupaten' => 'Situbondo', 'provinsi_id' =>35],
            ['id'=>   242, 'nama_kabupaten' => 'Probolinggo ', 'provinsi_id' =>35],
            ['id'=>   243, 'nama_kabupaten' => 'Pasuruan', 'provinsi_id' =>35],
            ['id'=>   244, 'nama_kabupaten' => 'Sidoarjo', 'provinsi_id' =>35],
            ['id'=>   245, 'nama_kabupaten' => 'Mojokerto', 'provinsi_id' =>35],
            ['id'=>   246, 'nama_kabupaten' => 'Jombang', 'provinsi_id' =>35],
            ['id'=>   247, 'nama_kabupaten' => 'Nganjuk', 'provinsi_id' =>35],
            ['id'=>   248, 'nama_kabupaten' => 'Madiun', 'provinsi_id' =>35],
            ['id'=>   249, 'nama_kabupaten' => 'Magetan', 'provinsi_id' =>35],
            ['id'=>   250, 'nama_kabupaten' => 'Ngawi', 'provinsi_id' =>35],
            ['id'=>   251, 'nama_kabupaten' => 'Bojonegoro ', 'provinsi_id' =>35],
            ['id'=>   252, 'nama_kabupaten' => 'Tuban', 'provinsi_id' =>35],
            ['id'=>   253, 'nama_kabupaten' => 'Lamongan', 'provinsi_id' =>35],
            ['id'=>   254, 'nama_kabupaten' => 'Gresik', 'provinsi_id' =>35],
            ['id'=>   255, 'nama_kabupaten' => 'Bangkalan ', 'provinsi_id' =>35],
            ['id'=>   256, 'nama_kabupaten' => 'Sampang', 'provinsi_id' =>35],
            ['id'=>   257, 'nama_kabupaten' => 'Pamekasan  ', 'provinsi_id' =>35],
            ['id'=>   258, 'nama_kabupaten' => 'Sumenep', 'provinsi_id' =>35],
            ['id'=>   259, 'nama_kabupaten' => 'Kota Kediri', 'provinsi_id' => 35],
            ['id'=>   260, 'nama_kabupaten' => 'Kota Blitar', 'provinsi_id' => 35],
            ['id'=>   261, 'nama_kabupaten' => 'Kota Malang', 'provinsi_id' => 35],
            ['id'=>   262, 'nama_kabupaten' => 'Kota Probolinggo', 'provinsi_id'=> 35],
            ['id'=>   263, 'nama_kabupaten' => 'Kota Pasuruan', 'provinsi_id' =>   35],
            ['id'=>   264, 'nama_kabupaten' => 'Kota Mojokerto', 'provinsi_id' =>  35],
            ['id'=>   265, 'nama_kabupaten' => 'Kota Madiun', 'provinsi_id'     => 35],
            ['id'=>   266, 'nama_kabupaten' => 'Kota Surabaya', 'provinsi_id' =>   35],
            ['id'=>   267, 'nama_kabupaten' => 'Kota Batu', 'provinsi_id' =>   35],
            ['id'=>   268, 'nama_kabupaten' => 'Pandeglang', 'provinsi_id' =>36],
            ['id'=>   269, 'nama_kabupaten' => 'Lebak', 'provinsi_id'     =>36],
            ['id'=>   270, 'nama_kabupaten' => 'Tangerang ', 'provinsi_id'   =>36],
            ['id'=>   271, 'nama_kabupaten' => 'Serang ', 'provinsi_id'     =>36],
            ['id'=>   272, 'nama_kabupaten' => 'Kota Tangerang', 'provinsi_id' =>  36],
            ['id'=>   273, 'nama_kabupaten' => 'Kota Cilegon', 'provinsi_id' =>    36],
            ['id'=>   274, 'nama_kabupaten' => 'Kota Serang', 'provinsi_id'     => 36],
            ['id'=>   275, 'nama_kabupaten' => 'Kota Tangerang Selatan', 'provinsi_id' => 36],
            ['id'=>   276, 'nama_kabupaten' => 'Jembrana', 'provinsi_id' =>51],
            ['id'=>   277, 'nama_kabupaten' => 'Tabanan', 'provinsi_id' =>51],
            ['id'=>   278, 'nama_kabupaten' => 'Badung', 'provinsi_id' => 51],
            ['id'=>   279, 'nama_kabupaten' => 'Gianyar', 'provinsi_id' => 51],
            ['id'=>   280, 'nama_kabupaten' => 'Klungkung   ', 'provinsi_id' => 51],
            ['id'=>   281, 'nama_kabupaten' => 'Bangli', 'provinsi_id' =>51],
            ['id'=>   282, 'nama_kabupaten' => 'Karang Asem', 'provinsi_id' => 51],
            ['id'=>   283, 'nama_kabupaten' => 'Buleleng', 'provinsi_id' =>51],
            ['id'=>   284, 'nama_kabupaten' => 'Kota Denpasar', 'provinsi_id' =>   51],
            ['id'=>   285, 'nama_kabupaten' => 'Lombok Barat', 'provinsi_id' =>    52],
            ['id'=>   286, 'nama_kabupaten' => 'Lombok Tengah', 'provinsi_id' =>   52],
            ['id'=>   287, 'nama_kabupaten' => 'Lombok Timur', 'provinsi_id' =>    52],
            ['id'=>   288, 'nama_kabupaten' => 'Sumbawa', 'provinsi_id'  =>     52],
            ['id'=>   289, 'nama_kabupaten' => 'Dompu', 'provinsi_id' =>52],
            ['id'=>   290, 'nama_kabupaten' => 'Bima', 'provinsi_id' =>52],
            ['id'=>   291, 'nama_kabupaten' => 'Sumbawa Barat', 'provinsi_id' =>   52],
            ['id'=>   292, 'nama_kabupaten' => 'Lombok Utara', 'provinsi_id' =>    52],
            ['id'=>   293, 'nama_kabupaten' => 'Kota Mataram', 'provinsi_id' =>    52],
            ['id'=>   294, 'nama_kabupaten' => 'Kota Bima', 'provinsi_id' =>   52],
            ['id'=>   295, 'nama_kabupaten' => 'Kupang', 'provinsi_id' => 53],
            ['id'=>   296, 'nama_kabupaten' => 'Timor Tengah Selatan', 'provinsi_id' => 53],
            ['id'=>   297, 'nama_kabupaten' => 'Timor Tengah Utara', 'provinsi_id' => 53],
            ['id'=>   298, 'nama_kabupaten' => 'Belu', 'provinsi_id' =>53],
            ['id'=>   299, 'nama_kabupaten' => 'Alor', 'provinsi_id' =>53],
            ['id'=>   300, 'nama_kabupaten' => 'Flores Timur', 'provinsi_id' =>53],
            ['id'=>   301, 'nama_kabupaten' => 'Sikka', 'provinsi_id' =>53],
            ['id'=>   302, 'nama_kabupaten' => 'Ende', 'provinsi_id' =>53],
            ['id'=>   303, 'nama_kabupaten' => 'Ngada', 'provinsi_id' =>53],
            ['id'=>   304, 'nama_kabupaten' => 'Manggarai', 'provinsi_id' =>53],
            ['id'=>   305, 'nama_kabupaten' => 'Sumba Barat', 'provinsi_id' => 53],
            ['id'=>   306, 'nama_kabupaten' => 'Sumba Timur', 'provinsi_id' => 53],
            ['id'=>   307, 'nama_kabupaten' => 'Lembata', 'provinsi_id' => 53],
            ['id'=>   308, 'nama_kabupaten' => 'Rote Ndao', 'provinsi_id' =>   53],
            ['id'=>   309, 'nama_kabupaten' => 'Manggarai Barat', 'provinsi_id' => 53],
            ['id'=>   310, 'nama_kabupaten' => 'Nagekeo', 'provinsi_id' =>53],
            ['id'=>   311, 'nama_kabupaten' => 'Sumba Tengah', 'provinsi_id' =>    53],
            ['id'=>   312, 'nama_kabupaten' => 'Sumba Barat Daya', 'provinsi_id' => 53],
            ['id'=>   313, 'nama_kabupaten' => 'Manggarai Timur', 'provinsi_id' => 53],
            ['id'=>   314, 'nama_kabupaten' => 'Sabu Raijua', 'provinsi_id' => 53],
            ['id'=>   315, 'nama_kabupaten' => 'Malaka', 'provinsi_id' =>53],
            ['id'=>   316, 'nama_kabupaten' => 'Kota Kupang', 'provinsi_id' => 53],
            ['id'=>   317, 'nama_kabupaten' => 'Sambas', 'provinsi_id' =>61],
            ['id'=>   318, 'nama_kabupaten' => 'Mempawah', 'provinsi_id' =>61],
            ['id'=>   319, 'nama_kabupaten' => 'Sanggau', 'provinsi_id' =>61],
            ['id'=>   320, 'nama_kabupaten' => 'Ketapang', 'provinsi_id' =>61],
            ['id'=>   321, 'nama_kabupaten' => 'Sintang', 'provinsi_id' =>61],
            ['id'=>   322, 'nama_kabupaten' => 'Kapuas Hulu', 'provinsi_id' => 61],
            ['id'=>   323, 'nama_kabupaten' => 'Bengkayang', 'provinsi_id' =>61],
            ['id'=>   324, 'nama_kabupaten' => 'Landak', 'provinsi_id' =>61],
            ['id'=>   325, 'nama_kabupaten' => 'Melawi', 'provinsi_id' =>61],
            ['id'=>   326, 'nama_kabupaten' => 'Sekadau', 'provinsi_id' =>61],
            ['id'=>   327, 'nama_kabupaten' => 'Kayong Utara', 'provinsi_id' =>61],
            ['id'=>   328, 'nama_kabupaten' => 'Kubu Raya', 'provinsi_id' =>   61],
            ['id'=>   329, 'nama_kabupaten' => 'Kota Pontianak', 'provinsi_id' =>  61],
            ['id'=>   330, 'nama_kabupaten' => 'Kota Singkawang', 'provinsi_id' => 61],
            ['id'=>   331, 'nama_kabupaten' => 'Kotawaringin Barat', 'provinsi_id' =>  62],
            ['id'=>   332, 'nama_kabupaten' => 'Kotawaringin Timur', 'provinsi_id' =>  62],
            ['id'=>   333, 'nama_kabupaten' => 'Kapuas', 'provinsi_id' =>62],
            ['id'=>   334, 'nama_kabupaten' => 'Barito Selatan', 'provinsi_id' =>  62],
            ['id'=>   335, 'nama_kabupaten' => 'Barito Utara', 'provinsi_id' =>    62],
            ['id'=>   336, 'nama_kabupaten' => 'Katingan', 'provinsi_id' =>62],
            ['id'=>   337, 'nama_kabupaten' => 'Seruyan', 'provinsi_id' =>62],
            ['id'=>   338, 'nama_kabupaten' => 'Sukamara', 'provinsi_id' =>62],
            ['id'=>   339, 'nama_kabupaten' => 'Lamandau', 'provinsi_id' =>62],
            ['id'=>   340, 'nama_kabupaten' => 'Gunung Mas', 'provinsi_id' =>  62],
            ['id'=>   341, 'nama_kabupaten' => 'Pulang Pisau', 'provinsi_id' =>    62],
            ['id'=>   342, 'nama_kabupaten' => 'Murung Raya', 'provinsi_id' => 62],
            ['id'=>   343, 'nama_kabupaten' => 'Barito Timur', 'provinsi_id' =>    62],
            ['id'=>   344, 'nama_kabupaten' => 'Kota Palangka Raya', 'provinsi_id' => 62],
            ['id'=>   345, 'nama_kabupaten' => 'Tanah Laut', 'provinsi_id' =>  63],
            ['id'=>   346, 'nama_kabupaten' => 'Kota Baru', 'provinsi_id' =>   63],
            ['id'=>   347, 'nama_kabupaten' => 'Banjar', 'provinsi_id' =>63],
            ['id'=>   348, 'nama_kabupaten' => 'Barito Kuala', 'provinsi_id' =>    63],
            ['id'=>   349, 'nama_kabupaten' => 'Tapin', 'provinsi_id' =>63],
            ['id'=>   350, 'nama_kabupaten' => 'Hulu Sungai Selatan', 'provinsi_id' => 63],
            ['id'=>   351, 'nama_kabupaten' => 'Hulu Sungai Tengah', 'provinsi_id' => 63],
            ['id'=>   352, 'nama_kabupaten' => 'Hulu Sungai Utara', 'provinsi_id' => 63],
            ['id'=>   353, 'nama_kabupaten' => 'Tabalong', 'provinsi_id' =>63],
            ['id'=>   354, 'nama_kabupaten' => 'Tanah Bumbu', 'provinsi_id' => 63],
            ['id'=>   355, 'nama_kabupaten' => 'Balangan', 'provinsi_id' =>63],
            ['id'=>   356, 'nama_kabupaten' => 'Kota Banjarmasin', 'provinsi_id' =>63],
            ['id'=>   357, 'nama_kabupaten' => 'Kota Banjar Baru', 'provinsi_id' =>63],
            ['id'=>   358, 'nama_kabupaten' => 'Paser', 'provinsi_id' =>64],
            ['id'=>   359, 'nama_kabupaten' => 'Kutai Kartanegara', 'provinsi_id' =>   64],
            ['id'=>   360, 'nama_kabupaten' => 'Berau', 'provinsi_id' =>64],
            ['id'=>   361, 'nama_kabupaten' => 'Kutai Barat', 'provinsi_id' => 64],
            ['id'=>   362, 'nama_kabupaten' => 'Kutai Timur', 'provinsi_id' => 64],
            ['id'=>   363, 'nama_kabupaten' => 'Penajam Paser Utara', 'provinsi_id' => 64],
            ['id'=>   364, 'nama_kabupaten' => 'Mahakam Hulu', 'provinsi_id' =>    64],
            ['id'=>   365, 'nama_kabupaten' => 'Kota Balikpapan', 'provinsi_id' => 64],
            ['id'=>   366, 'nama_kabupaten' => 'Kota Samarinda', 'provinsi_id' =>  64],
            ['id'=>   367, 'nama_kabupaten' => 'Kota Bontang', 'provinsi_id' =>    64],
            ['id'=>   368, 'nama_kabupaten' => 'Bulungan', 'provinsi_id' =>65],
            ['id'=>   369, 'nama_kabupaten' => 'Malinau', 'provinsi_id' =>65],
            ['id'=>   370, 'nama_kabupaten' => 'Nunukan', 'provinsi_id' =>65],
            ['id'=>   371, 'nama_kabupaten' => 'Tana Tidung', 'provinsi_id' => 65],
            ['id'=>   372, 'nama_kabupaten' => 'Kota Tarakan', 'provinsi_id' =>    65],
            ['id'=>   373, 'nama_kabupaten' => 'Bolaang Mongondow', 'provinsi_id' =>   71],
            ['id'=>   374, 'nama_kabupaten' => 'Minahasa', 'provinsi_id' => 71],
            ['id'=>   375, 'nama_kabupaten' => 'Kepulauan Sangihe', 'provinsi_id' =>   71],
            ['id'=>   376, 'nama_kabupaten' => 'Kepulauan Talaud', 'provinsi_id' =>    71],
            ['id'=>   377, 'nama_kabupaten' => 'Minahasa Selatan', 'provinsi_id' =>    71],
            ['id'=>   378, 'nama_kabupaten' => 'Minahasa Utara', 'provinsi_id' =>  71],
            ['id'=>   379, 'nama_kabupaten' => 'Bolaang Mongondow Utara', 'provinsi_id' => 71],
            ['id'=>   380, 'nama_kabupaten' => 'Minahasa Tenggara', 'provinsi_id' =>   71],
            ['id'=>   381, 'nama_kabupaten' => 'Siau Tagulandang Biaro', 'provinsi_id' => 71],
            ['id'=>   382, 'nama_kabupaten' => 'Bolaang Mongondow Timur', 'provinsi_id' => 71],
            ['id'=>   383, 'nama_kabupaten' => 'Bolaang Mongondow Selatan', 'provinsi_id' => 71],
            ['id'=>   384, 'nama_kabupaten' => 'Kota Manado', 'provinsi_id' => 71],
            ['id'=>   385, 'nama_kabupaten' => 'Kota Bitung', 'provinsi_id' => 71],
            ['id'=>   386, 'nama_kabupaten' => 'Kota Tomohon', 'provinsi_id' => 71],
            ['id'=>   387, 'nama_kabupaten' => 'Kota Kotamobagu', 'provinsi_id' => 71],
            ['id'=>   388, 'nama_kabupaten' => 'Banggai', 'provinsi_id' =>72],
            ['id'=>   389, 'nama_kabupaten' => 'Poso', 'provinsi_id' =>72],
            ['id'=>   390, 'nama_kabupaten' => 'Donggala', 'provinsi_id' =>72],
            ['id'=>   391, 'nama_kabupaten' => 'Toli-Toli', 'provinsi_id' =>   72],
            ['id'=>   392, 'nama_kabupaten' => 'Buol', 'provinsi_id' =>  72],
            ['id'=>   393, 'nama_kabupaten' => 'Morowali', 'provinsi_id' =>72],
            ['id'=>   394, 'nama_kabupaten' => 'Morowali Utara', 'provinsi_id' =>  72],
            ['id'=>   395, 'nama_kabupaten' => 'Banggai Laut', 'provinsi_id' =>    72],
            ['id'=>   396, 'nama_kabupaten' => 'Banggai Kepulauan', 'provinsi_id' =>   72],
            ['id'=>   397, 'nama_kabupaten' => 'Parigi Moutong', 'provinsi_id' =>  72],
            ['id'=>   398, 'nama_kabupaten' => 'Tojo Una-Una', 'provinsi_id' =>72],
            ['id'=>   399, 'nama_kabupaten' => 'Sigi', 'provinsi_id' =>72],
            ['id'=>   400, 'nama_kabupaten' => 'Kota Palu', 'provinsi_id' =>   72],
            ['id'=>   401, 'nama_kabupaten' => 'Kepulauan Selayar', 'provinsi_id' =>   73],
            ['id'=>   402, 'nama_kabupaten' => 'Bulukumba', 'provinsi_id' =>73],
            ['id'=>   403, 'nama_kabupaten' => 'Bantaeng', 'provinsi_id' =>73],
            ['id'=>   404, 'nama_kabupaten' => 'Jeneponto', 'provinsi_id' =>73],
            ['id'=>   405, 'nama_kabupaten' => 'Takalar', 'provinsi_id' =>73],
            ['id'=>   406, 'nama_kabupaten' => 'Gowa', 'provinsi_id' =>73],
            ['id'=>   407, 'nama_kabupaten' => 'Sinjai', 'provinsi_id' =>73],
            ['id'=>   408, 'nama_kabupaten' => 'Bone', 'provinsi_id' =>73],
            ['id'=>   409, 'nama_kabupaten' => 'Maros', 'provinsi_id' =>73],
            ['id'=>   410, 'nama_kabupaten' => 'Pangkajene Dan Kepulauan', 'provinsi_id' => 73],
            ['id'=>   411, 'nama_kabupaten' => 'Barru', 'provinsi_id' =>73],
            ['id'=>   412, 'nama_kabupaten' => 'Soppeng', 'provinsi_id' =>73],
            ['id'=>   413, 'nama_kabupaten' => 'Wajo', 'provinsi_id' =>73],
            ['id'=>   414, 'nama_kabupaten' => 'Sidenreng Rappang', 'provinsi_id' =>   73],
            ['id'=>   415, 'nama_kabupaten' => 'Pinrang', 'provinsi_id' =>73],
            ['id'=>   416, 'nama_kabupaten' => 'Enrekang', 'provinsi_id' =>73],
            ['id'=>   417, 'nama_kabupaten' => 'Luwu', 'provinsi_id' =>73],
            ['id'=>   418, 'nama_kabupaten' => 'Tana Toraja', 'provinsi_id' => 73],
            ['id'=>   419, 'nama_kabupaten' => 'Toraja Utara', 'provinsi_id' =>    73],
            ['id'=>   420, 'nama_kabupaten' => 'Luwu Utara', 'provinsi_id' =>  73],
            ['id'=>   421, 'nama_kabupaten' => 'Luwu Timur', 'provinsi_id' =>  73],
            ['id'=>   422, 'nama_kabupaten' => 'Kota Makassar', 'provinsi_id' =>   73],
            ['id'=>   423, 'nama_kabupaten' => 'Kota Parepare', 'provinsi_id' =>   73],
            ['id'=>   424, 'nama_kabupaten' => 'Kota Palopo', 'provinsi_id' => 73],
            ['id'=>   425, 'nama_kabupaten' => 'Kolaka', 'provinsi_id' =>74],
            ['id'=>   426, 'nama_kabupaten' => 'Konawe', 'provinsi_id' =>74],
            ['id'=>   427, 'nama_kabupaten' => 'Konawe Kepulauan', 'provinsi_id' =>    74],
            ['id'=>   428, 'nama_kabupaten' => 'Muna', 'provinsi_id' =>74],
            ['id'=>   429, 'nama_kabupaten' => 'Buton', 'provinsi_id' =>74],
            ['id'=>   430, 'nama_kabupaten' => 'Konawe Selatan', 'provinsi_id' =>  74],
            ['id'=>   431, 'nama_kabupaten' => 'Bombana', 'provinsi_id' =>74],
            ['id'=>   432, 'nama_kabupaten' => 'Wakatobi', 'provinsi_id' =>74],
            ['id'=>   433, 'nama_kabupaten' => 'Kolaka Utara', 'provinsi_id' =>74],
            ['id'=>   434, 'nama_kabupaten' => 'Buton Utara', 'provinsi_id' => 74],
            ['id'=>   435, 'nama_kabupaten' => 'Konawe Utara', 'provinsi_id' =>74],
            ['id'=>   436, 'nama_kabupaten' => 'Kolaka Timur', 'provinsi_id' =>74],
            ['id'=>   437, 'nama_kabupaten' => 'Kota Kendari', 'provinsi_id' =>74],
            ['id'=>   438, 'nama_kabupaten' => 'Kota Baubau', 'provinsi_id' => 74],
            ['id'=>   439, 'nama_kabupaten' => 'Gorontalo', 'provinsi_id' => 75],
            ['id'=>   440, 'nama_kabupaten' => 'Boalemo', 'provinsi_id' =>75],
            ['id'=>   441, 'nama_kabupaten' => 'Bone Bolango', 'provinsi_id' =>75],
            ['id'=>   442, 'nama_kabupaten' => 'Pohuwato', 'provinsi_id' =>75],
            ['id'=>   443, 'nama_kabupaten' => 'Gorontalo Utara', 'provinsi_id' => 75],
            ['id'=>   444, 'nama_kabupaten' => 'Kota Gorontalo', 'provinsi_id' =>  75],
            ['id'=>   445, 'nama_kabupaten' => 'Mamuju Utara', 'provinsi_id' =>    76],
            ['id'=>   446, 'nama_kabupaten' => 'Mamuju', 'provinsi_id' =>76],
            ['id'=>   447, 'nama_kabupaten' => 'Mamasa', 'provinsi_id' =>76],
            ['id'=>   448, 'nama_kabupaten' => 'Polewali Mandar', 'provinsi_id' => 76],
            ['id'=>   449, 'nama_kabupaten' => 'Majene', 'provinsi_id' =>76],
            ['id'=>   450, 'nama_kabupaten' => 'Mamuju Tengah', 'provinsi_id' =>   76],
            ['id'=>   451, 'nama_kabupaten' => 'Maluku Tengah', 'provinsi_id' =>   81],
            ['id'=>   452, 'nama_kabupaten' => 'Maluku Tenggara', 'provinsi_id' => 81],
            ['id'=>   453, 'nama_kabupaten' => 'Maluku Tenggara Barat', 'provinsi_id' => 81],
            ['id'=>   454, 'nama_kabupaten' => 'Buru', 'provinsi_id' =>81],
            ['id'=>   455, 'nama_kabupaten' => 'Seram Bagian Timur', 'provinsi_id' => 81],
            ['id'=>   456, 'nama_kabupaten' => 'Seram Bagian Barat', 'provinsi_id' => 81],
            ['id'=>   457, 'nama_kabupaten' => 'Kepulauan Aru', 'provinsi_id' =>   81],
            ['id'=>   458, 'nama_kabupaten' => 'Maluku Barat Daya', 'provinsi_id' => 81],
            ['id'=>   459, 'nama_kabupaten' => 'Buru Selatan', 'provinsi_id' =>    81],
            ['id'=>   460, 'nama_kabupaten' => 'Kota Ambon', 'provinsi_id' =>  81],
            ['id'=>   461, 'nama_kabupaten' => 'Kota Tual', 'provinsi_id' =>   81],
            ['id'=>   462, 'nama_kabupaten' => 'Halmahera Barat', 'provinsi_id' => 82],
            ['id'=>   463, 'nama_kabupaten' => 'Halmahera Tengah', 'provinsi_id' =>    82],
            ['id'=>   464, 'nama_kabupaten' => 'Halmahera Utara', 'provinsi_id' => 82],
            ['id'=>   465, 'nama_kabupaten' => 'Halmahera Selatan', 'provinsi_id' =>   82],
            ['id'=>   466, 'nama_kabupaten' => 'Kepulauan Sula', 'provinsi_id' =>  82],
            ['id'=>   467, 'nama_kabupaten' => 'Halmahera Timur', 'provinsi_id' => 82],
            ['id'=>   468, 'nama_kabupaten' => 'Pulau Morotai', 'provinsi_id' =>   82],
            ['id'=>   469, 'nama_kabupaten' => 'Pulau Taliabu', 'provinsi_id' =>   82],
            ['id'=>   470, 'nama_kabupaten' => 'Kota Ternate', 'provinsi_id' =>    82],
            ['id'=>   471, 'nama_kabupaten' => 'Kota Tidore Kepulauan', 'provinsi_id' => 82],
            ['id'=>   472, 'nama_kabupaten' => 'Merauke', 'provinsi_id' =>91],
            ['id'=>   473, 'nama_kabupaten' => 'Jayawijaya', 'provinsi_id' =>91],
            ['id'=>   474, 'nama_kabupaten' => 'Jayapura', 'provinsi_id' =>91],
            ['id'=>   475, 'nama_kabupaten' => 'Nabire', 'provinsi_id' =>91],
            ['id'=>   476, 'nama_kabupaten' => 'Kepulauan Yapen', 'provinsi_id' => 91],
            ['id'=>   477, 'nama_kabupaten' => 'Biak Numfor', 'provinsi_id' => 91],
            ['id'=>   478, 'nama_kabupaten' => 'Puncak Jaya', 'provinsi_id' => 91],
            ['id'=>   479, 'nama_kabupaten' => 'Paniai', 'provinsi_id' =>91],
            ['id'=>   480, 'nama_kabupaten' => 'Mimika', 'provinsi_id' =>91],
            ['id'=>   481, 'nama_kabupaten' => 'Sarmi', 'provinsi_id' =>91],
            ['id'=>   482, 'nama_kabupaten' => 'Keerom', 'provinsi_id' =>91],
            ['id'=>   483, 'nama_kabupaten' => 'Pegunungan Bintang', 'provinsi_id' =>  91],
            ['id'=>   484, 'nama_kabupaten' => 'Yahukimo', 'provinsi_id' =>91],
            ['id'=>   485, 'nama_kabupaten' => 'Tolikara', 'provinsi_id' =>91],
            ['id'=>   486, 'nama_kabupaten' => 'Waropen', 'provinsi_id' =>91],
            ['id'=>   487, 'nama_kabupaten' => 'Boven Digoel', 'provinsi_id' =>    91],
            ['id'=>   488, 'nama_kabupaten' => 'Mappi', 'provinsi_id' =>91],
            ['id'=>   489, 'nama_kabupaten' => 'Asmat', 'provinsi_id' =>91],
            ['id'=>   490, 'nama_kabupaten' => 'Lanny Jaya', 'provinsi_id' =>  91],
            ['id'=>   491, 'nama_kabupaten' => 'Nduga', 'provinsi_id' =>91],
            ['id'=>   492, 'nama_kabupaten' => 'Supiori', 'provinsi_id' =>91],
            ['id'=>   493, 'nama_kabupaten' => 'Intan Jaya', 'provinsi_id' => 91],
            ['id'=>   494, 'nama_kabupaten' => 'Puncak', 'provinsi_id' =>91],
            ['id'=>   495, 'nama_kabupaten' => 'Deiyai', 'provinsi_id' =>91],
            ['id'=>   496, 'nama_kabupaten' => 'Dogiyai', 'provinsi_id' =>91],
            ['id'=>   497, 'nama_kabupaten' => 'Yalimo', 'provinsi_id' =>91],
            ['id'=>   498, 'nama_kabupaten' => 'Mamberamo Tengah', 'provinsi_id' =>    91],
            ['id'=>   499, 'nama_kabupaten' => 'Mamberamo Raya', 'provinsi_id' =>  91],
            ['id'=>   500, 'nama_kabupaten' => 'Kota Jayapura', 'provinsi_id' =>   91],
            ['id'=>   501, 'nama_kabupaten' => 'Sorong', 'provinsi_id' =>92],
            ['id'=>   502, 'nama_kabupaten' => 'Manokwari', 'provinsi_id' =>92],
            ['id'=>   503, 'nama_kabupaten' => 'Fakfak', 'provinsi_id' =>92],
            ['id'=>   504, 'nama_kabupaten' => 'Sorong Selatan', 'provinsi_id' =>  92],
            ['id'=>   505, 'nama_kabupaten' => 'Raja Ampat', 'provinsi_id' =>  92],
            ['id'=>   506, 'nama_kabupaten' => 'Teluk Bintuni', 'provinsi_id' =>   92],
            ['id'=>   507, 'nama_kabupaten' => 'Teluk Wondama', 'provinsi_id' =>   92],
            ['id'=>   508, 'nama_kabupaten' => 'Kaimana', 'provinsi_id' =>92],
            ['id'=>   509, 'nama_kabupaten' => 'Maybrat', 'provinsi_id' =>92],
            ['id'=>   510, 'nama_kabupaten' => 'Tambrauw', 'provinsi_id' =>92],
            ['id'=>   511, 'nama_kabupaten' => 'Pegunungan Arfak', 'provinsi_id' =>    92],
            ['id'=>   512, 'nama_kabupaten' => 'Manokwari Selatan', 'provinsi_id' =>   92],
            ['id'=>   513, 'nama_kabupaten' => 'Kota Sorong', 'provinsi_id' => 92],

        ];

        DB::table('ref_kabupaten')->insert($data);
    }
}
